version: "3.9"

networks:
  teamops:
    driver: bridge

volumes:
  db_data:
  npm_data:
  npm_letsencrypt:
  kuma_data:
  nextcloud_data:
  nextcloud_db_data:

services:

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-teamops}
      POSTGRES_USER: ${POSTGRES_USER:-teamops}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teamops-db-pass-STRONG}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [ teamops ]

  backend:
    build: ./backend
    # (switch to an image later if you use GHCR)
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://teamops:${POSTGRES_PASSWORD:-teamops-db-pass-STRONG}@db:5432/${POSTGRES_DB:-teamops}}
      BACKEND_SECRET: ${BACKEND_SECRET:-super-secret-long-random}
      PVE_HOST: ${PVE_HOST:-https://192.168.1.22:8006}
      PVE_TOKEN_ID: ${PVE_TOKEN_ID:-teamops@pve!dash}
      PVE_TOKEN_SECRET: ${PVE_TOKEN_SECRET:-set-proxmox-token}
      NEXTCLOUD_BASE: ${NEXTCLOUD_BASE:-http://nextcloud}
      NEXTCLOUD_ADMIN: ${NEXTCLOUD_ADMIN:-admin}
      NEXTCLOUD_ADMIN_PASS: ${NEXTCLOUD_ADMIN_PASS:-change-me}
      KUMA_URL: ${KUMA_URL:-http://kuma:3001}
      KUMA_TOKEN: ${KUMA_TOKEN:-}
      AI_API_BASE: ${AI_API_BASE:-https://api.openai.com/v1}
      AI_API_KEY: ${AI_API_KEY:-}
      AI_MODEL: ${AI_MODEL:-gpt-4o-mini}
      AI_TIMEOUT: ${AI_TIMEOUT:-45}
    depends_on: [ db ]
    ports:
      - "8000:8000"
    networks: [ teamops ]

  dashy:
    image: lissy93/dashy:2.1.1
    restart: unless-stopped
    volumes:
      - ./dashy/conf.yml:/app/user-data/conf.yml
    networks: [ teamops ]
    # no ports here; expose via NPM at dashboard.liork.cloud

  npm:
    image: jc21/nginx-proxy-manager:2.11.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks: [ teamops ]

  kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    environment:
      - DISABLE_FRAME_SAMEORIGIN=true
    volumes:
      - kuma_data:/app/data
    networks: [ teamops ]
    # expose via NPM at status.liork.cloud

  nextcloud_db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ncroot-pass-STRONG}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-nextcloud-pass-STRONG}
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks: [ teamops ]

  nextcloud_redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks: [ teamops ]

  nextcloud:
    image: nextcloud:29-apache
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-nextcloud_db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-nextcloud-pass-STRONG}
      REDIS_HOST: ${REDIS_HOST:-nextcloud_redis}
    depends_on: [ nextcloud_db, nextcloud_redis ]
    volumes:
      - nextcloud_data:/var/www/html
    networks: [ teamops ]
