services:
  npm:
    image: jc21/nginx-proxy-manager:2.11.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - teamops

  dashy:
    image: lissy93/dashy:2.1.1
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./dashy/conf.yml:/app/public/conf.yml
    depends_on:
      - backend
      - kuma
    networks:
      - teamops

  kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    environment:
      - DISABLE_FRAME_SAMEORIGIN=true   # <— allow embedding in Dashy iframe
    volumes:
      - kuma_data:/app/data
    networks:
      - teamops

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - teamops

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - BACKEND_SECRET=${BACKEND_SECRET}
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PVE_HOST=${PVE_HOST}
      - PVE_TOKEN_ID=${PVE_TOKEN_ID}
      - PVE_TOKEN_SECRET=${PVE_TOKEN_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - NEXTCLOUD_BASE=http://nextcloud
      - NEXTCLOUD_ADMIN=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASS=${NC_ADMIN_PASS}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - teamops

  nextcloud:
    image: nextcloud:29-apache
    restart: unless-stopped
    environment:
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_FQDN} nextcloud
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    networks:
      - teamops

  nextcloud_db:
    image: mariadb:11
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=${POSTGRES_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - teamops

  nextcloud_redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - teamops

volumes:
  npm_data:
  npm_letsencrypt:
  kuma_data:
  db_data:
  nextcloud_data:
  nextcloud_db_data:

networks:
  teamops:
    driver: bridge
